name: Build Extension

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Fast CLI
        run: |
          pip install fast-cli

      - name: Build Extension with Fast
        run: |
          fast build

      - name: Upload AIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Media3Player-AIX
          path: out/*.aix

